name: Generate Wiki from GitHub Docs

on:
    push:
      branches: [ "master" ]
      paths: ["documentation/**", ".github/workflows/wiki.yml"]
jobs:
    update-wiki:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Sync Wiki
        uses: cmbrose/github-docs-to-wiki@v0.24
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          defaultBranch: master
          rootDocsFolder: ./documentation
          convertRootReadmeToHomePage: true
          useHeaderForWikiName: true
          customCommitMessageFormat: ':gem: Chore: Sync Docs to GH Wiki'